version: 2
project_name: goreleaser-git-env-bug

env:
  - COMMIT_HASH={{.FullCommit}}
  - COMMIT_TIMESTAMP={{.CommitTimestamp}}
  - COMMIT_DATE={{.CommitDate}}
  - PROJECT_NAME={{.ProjectName}}
  - FOO=bar

before:
  hooks:
    - sh -c 'echo COMMIT_HASH=$COMMIT_HASH'
    - sh -c 'echo COMMIT_TIMESTAMP=$COMMIT_TIMESTAMP'
    - sh -c 'echo COMMIT_DATE=$COMMIT_DATE'
    - sh -c 'echo PROJECT_NAME=$PROJECT_NAME'
    - sh -c 'echo FOO=$FOO'

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - go_first_class
